global using Material.Components.Maui.Core;
global using Material.Components.Maui.Core.Interfaces;
global using Material.Components.Maui.Extensions;
global using Material.Components.Maui.Tokens;
global using Maui.BindableProperty.Generator.Core;
global using SkiaSharp;
global using SkiaSharp.Views.Maui;
global using SkiaSharp.Views.Maui.Controls;
global using System.Runtime.CompilerServices;
global using IBackgroundElement = Material.Components.Maui.Core.Interfaces.IBackgroundElement;
global using ICommandElement = Material.Components.Maui.Core.Interfaces.ICommandElement;
global using IContextMenu = Material.Components.Maui.Core.Interfaces.IContextMenu;
global using IElevationElement = Material.Components.Maui.Core.Interfaces.IElevationElement;
global using IForegroundElement = Material.Components.Maui.Core.Interfaces.IForegroundElement;
global using IIconElement = Material.Components.Maui.Core.Interfaces.IIconElement;
global using IOutlineElement = Material.Components.Maui.Core.Interfaces.IOutlineElement;
global using IPaddingElement = Material.Components.Maui.Core.Interfaces.IPaddingElement;
global using IRippleElement = Material.Components.Maui.Core.Interfaces.IRippleElement;
global using IShapeElement = Material.Components.Maui.Core.Interfaces.IShapeElement;
global using IStateLayerElement = Material.Components.Maui.Core.Interfaces.IStateLayerElement;
global using ITextElement = Material.Components.Maui.Core.Interfaces.ITextElement;
global using ITouchElement = Material.Components.Maui.Core.Interfaces.ITouchElement;
global using IView = Material.Components.Maui.Core.Interfaces.IView;
global using ValueChangedEventArgs = Material.Components.Maui.Core.ValueChangedEventArgs;
global using FontMapper = Material.Components.Maui.Tokens.FontMapper;
global using TextAlignment = Microsoft.Maui.TextAlignment;
global using TextStyle = Topten.RichTextKit.Style;
