global using Material.Components.Maui.Extensions;
global using Material.Components.Maui.Tokens;
global using Maui.BindableProperty.Generator.Core;
global using SkiaSharp;
global using SkiaSharp.Views.Maui;
global using SkiaSharp.Views.Maui.Controls;
global using MButton = Material.Components.Maui.Button;
global using MIconButton = Material.Components.Maui.IconButton;
global using MCard = Material.Components.Maui.Card;
global using MCheckBox = Material.Components.Maui.CheckBox;
global using MChip = Material.Components.Maui.Chip;
global using MComboBox = Material.Components.Maui.ComboBox;
global using MFAB = Material.Components.Maui.FAB;
global using MLabel = Material.Components.Maui.Label;
global using MNavigationBar = Material.Components.Maui.NavigationBar;
global using MRadioButton = Material.Components.Maui.RadioButton;
global using MSwitch = Material.Components.Maui.Switch;
global using TextStyle = Topten.RichTextKit.Style;
global using FontMapper = Material.Components.Maui.Tokens.FontMapper;
global using IBackgroundElement = Material.Components.Maui.Core.Interfaces.IBackgroundElement;
global using IElevationElement = Material.Components.Maui.Core.Interfaces.IElevationElement;
global using FontAttributes = Material.Components.Maui.Tokens.FontAttributes;
global using TextAlignment = Microsoft.Maui.TextAlignment;
global using IForegroundElement = Material.Components.Maui.Core.Interfaces.IForegroundElement;
global using IImageElement = Material.Components.Maui.Core.Interfaces.IImageElement;
global using IMenuItem = Material.Components.Maui.Core.Interfaces.IMenuItem;
global using IOutlineElement = Material.Components.Maui.Core.Interfaces.IOutlineElement;
global using IPopup = Material.Components.Maui.Core.Interfaces.IPopup;
global using IRippleElement = Material.Components.Maui.Core.Interfaces.IRippleElement;
global using IShapeElement = Material.Components.Maui.Core.Interfaces.IShapeElement;
global using IStateLayerElement = Material.Components.Maui.Core.Interfaces.IStateLayerElement;
global using ITextElement = Material.Components.Maui.Core.Interfaces.ITextElement;
global using ITouchElement = Material.Components.Maui.Core.Interfaces.ITouchElement;
global using IView = Material.Components.Maui.Core.Interfaces.IView;